### ISSUE TITLE
mms数据集复现B域结果差距较大

### ISSUE THREAD

**Issue by lkfiean** [HiLab-git/UPL-SFDA#3]
作者你好，我对您的工作很感兴趣，但是我在复现结果时体现出了一些较大差距，想请您帮助分析一下问题原因。
参数完全按照您的论文设置，学习率设置的0.0001，显卡为2080ti，torch版本为1.8.1
结果来看c域d域比您的论文几乎低1个百分点以内，但b域差了3个点
![1](https://github.com/HiLab-git/UPL-SFDA/assets/130351987/1e58afdd-1277-4c14-9740-b331dbca2078)

**Comment by JianghaoWu** [comment]
I am sorry to hear this news. Indeed, due to the different controlled variables, it has led to inconsistencies with the results in the article. I have a suggestion: try adjusting the learning rate to lr = 0.00001, which should yield better results. If you still encounter issues, please feel free to contact me, and we can work together to identify the problem.

**Comment by lkfiean** [comment]
我看了您对另一位提问者的回答，尝试调整学习率到0.00001，结果如下所示
![2](https://github.com/HiLab-git/UPL-SFDA/assets/130351987/7d61d3ab-8de6-4e47-95d1-f94fedcaedc4)
事实上，我从0.0009-0.00001之间尝试了20次实验，结果最好的差不多为学习率为0.00007，结果和为0.0001时差不多，而且几乎都时在第1轮的时候模型就在验证集达到了最好的指标

**Comment by JianghaoWu** [comment]
Thank you for your attention. In the original text, the average value in our domain B is 87.04. Our multiple experimental results, including ablation experiments, consistently show similar results. The difference of 1.7 points from the 85.34 you reported could be due to various reasons. You just need to report your own experimental data in your results. In addition, please feel free to contact me if you have any further questions.

**Comment by lkfiean** [comment]
好的感谢，主要是我是怕我遗漏了什么导致没有复现出该有的效果，我换个设备在试验一下，非常感谢您的回答
